---

# Initialize master server and get join command for workers

  - name: Initialize Kubernetes master
    command: kubeadm init --pod-network-cidr=10.244.0.0/16

  - name: Print join command on master server
    shell: kubeadm token create --print-join-command > /tmp/join_command

  - name: Fetch join command from master to local machine
    fetch:
      src: /tmp/join_command
      dest: buffer/join_command
      flat: yes

  - name: Clean up /tmp/join_command
    file:
      path: /tmp/join_command
      state: absent

# Set up kubectl

  - name: Ensure that /root/.kube directory exists
    file:
      path: /root/.kube
      state: directory
      mode: '0755'

  - name: Copy admin.conf to .kube/config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      remote_src: yes

  - name: Install Flannel 
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml